// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CStubMKGui.Model.template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class HeaderStubTemplate : StubCodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"

	PushIndent("    ");
	var indent = CurrentIndent;
	ClearIndent();

            
            #line default
            #line hidden
            this.Write("#pragma once\r\n\r\n//スタブのバッファの宣言\r\n");
            
            #line 14 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"
 foreach (var func in Functions) { 
            
            #line default
            #line hidden
            
            #line 15 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"

	WriteLine($"extern int {func.Name}_called_count;");
	foreach (var argument in func.Parameters) {
		WriteLine($"extern {argument.DataType}\t{func.Name}_{argument.Name}[100];");
	}
	WriteLine($"extern {func.DataType}\t{func.Name}_return[100];");

            
            #line default
            #line hidden
            this.Write("\r\n//スタブの初期化関数\r\n");
            
            #line 24 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"

	WriteLine($"void {func.Name}_Stub_Init();");

            
            #line default
            #line hidden
            
            #line 27 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\HeaderStubTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
