// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CStubMKGui.Model.template
{
    using CStubMKGui.Model;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SourceStubTemplate : StubCodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	PushIndent("    ");
	var indent = CurrentIndent;
	ClearIndent();

            
            #line default
            #line hidden
            this.Write("#include <stdio.h>\r\n\r\n//スタブのバッファの宣言\r\n");
            
            #line 12 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 foreach (var func in Functions) { 
            
            #line default
            #line hidden
            
            #line 13 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	foreach (var argument in func.Parameters) {
		WriteLine($"{argument.DataType}{indent}{func.Name}_{argument.Name}[100];");
	}

            
            #line default
            #line hidden
            
            #line 18 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n//スタブの初期化関数\r\n");
            
            #line 21 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 foreach (var func in Functions) { 
            
            #line default
            #line hidden
            
            #line 22 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	WriteLine($"void {func.Name}_Stub_Init()");
	WriteLine("{");

	//呼び出し回数の初期化
	WriteLine($"{indent}{func.Name}_called_count = 0;");
	WriteLine($"{indent}for (int index = 0; index < 100; index++) {{");
	foreach (var argument in func.Parameters) {
		if (IsVariable(argument)) {
			WriteLine($"{indent}{indent}{func.Name}_{argument.Name}[index] = 0;");
		}
	}
	WriteLine($"{indent}}}");
	WriteLine($"{indent}{func.Name}_return[index] = 0;");
	WriteLine("}");

            
            #line default
            #line hidden
            
            #line 38 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("//スタブ本体\r\n");
            
            #line 40 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 foreach (var func in Functions) { 
            
            #line default
            #line hidden
            
            #line 41 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(func.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n(\r\n");
            
            #line 43 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 
	//スタブの引数一覧
	int paramCount = func.Parameters.Count();
	for (int index = 0; index < paramCount; index++) {
		var paramItem = func.Parameters.ElementAt(index);
		Write($"{indent}{paramItem.ToString()}");
		if (index != (paramCount - 1)) {
			WriteLine(",");
		}
		else
		{
			WriteLine("");
		}
	}

            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 60 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	//スタブの戻り値の確認
	if (IsVariable(func)) {
		WriteLine($"{indent}{func.DataType} returnLatch = {func.Name}[{func.Name}_called_count];");
	}

            
            #line default
            #line hidden
            
            #line 66 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	//引数の格納
	foreach (var argument in func.Parameters) {
		if (IsVariable(argument)) {
			WriteLine($"{indent}{func.Name}_{argument.Name}[{func.Name}_called_count] = {argument.Name};");
		}
	}

            
            #line default
            #line hidden
            
            #line 74 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	//値の出力
	var outputArgs = func.Parameters.Where(argument => argument.Mode == Param.AccessMode.Out);
	foreach (var outputArg in outputArgs) {
		WriteLine($"{indent}*{outputArg.Name} = {func.Name}_{outputArg.Name}_value[{func.Name}_called_count];");
	}

            
            #line default
            #line hidden
            
            #line 81 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	//呼び出し回数の更新
	WriteLine($"{indent}{func.Name}_called_count++;");

            
            #line default
            #line hidden
            
            #line 85 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"

	//スタブの戻り値を返す。
	if (IsVariable(func)) {
		WriteLine($"{indent}return returnLatch;");
	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 92 "E:\development\CStubMk\dev\dev\CStubMKGui\Model\template\SourceStubTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
