// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\HeaderStubTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class HeaderStubTemplate : StubCodeTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("//関数のバッファサイズのマクロ\r\n");
            
            #line 8 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\HeaderStubTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateStubBufferSizeMacroDefine()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//スタブのバッファの外部宣言\r\n");
            
            #line 11 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\HeaderStubTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateBufferDeclareCode()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//スタブの初期化関数\r\n");
            
            #line 14 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\HeaderStubTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateBufferInitCode()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
