// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferExternDeclarationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubBufferExternDeclarationTemplate : StubBufferDeclarationTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n//関数の呼び出し回数\r\n");
            
            #line 9 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferExternDeclarationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncCalledCounterBufferDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//関数の戻り値\r\n");
            
            #line 12 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferExternDeclarationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncReturnValueDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//引数\r\n");
            
            #line 15 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferExternDeclarationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnValueViaArgumentBufferDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//引数経由の戻り値\r\n");
            
            #line 18 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferExternDeclarationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnValueSizeViaArgumentBufferDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
