// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferSizeMacroDefineTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubBufferSizeMacroDefineTemplate : StubCodeTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("#define\t");
            
            #line 7 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferSizeMacroDefineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubBufferSizeMacro1()));
            
            #line default
            #line hidden
            this.Write("\t\t(");
            
            #line 7 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferSizeMacroDefineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubBufferSize1()));
            
            #line default
            #line hidden
            this.Write(")\r\n#define\t");
            
            #line 8 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferSizeMacroDefineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubBufferSizeMacro2()));
            
            #line default
            #line hidden
            this.Write("\t\t(");
            
            #line 8 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferSizeMacroDefineTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubBufferSize2()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
