// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubSourceBodyTemplate : StubCodeTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubBodyEntryPoint()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t//スタブの戻り値のラッチ\r\n");
            
            #line 10 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LatchReturnValue()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//引数のバッファへの格納\r\n");
            
            #line 13 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BackupArgToBuffer()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//ポインタ引数を介した戻り値\r\n");
            
            #line 16 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnValueViaPointer()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//呼び出し回数の更新\r\n");
            
            #line 19 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateCalledCounter()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//関数戻り値\r\n");
            
            #line 22 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubSourceBodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnValue()));
            
            #line default
            #line hidden
            this.Write("\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
