// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubBufferInitTemplate : StubCodeTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubInitializeEntryPoint()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t//呼び出し回数の初期化\r\n");
            
            #line 10 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncCalledCountInitCode));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
	if (!(string.IsNullOrEmpty(FuncReturnValueInitCode))) {	
            
            #line default
            #line hidden
            this.Write("\r\n\t//戻り値の初期化\r\n");
            
            #line 14 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncReturnValueInit()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
	}	
            
            #line default
            #line hidden
            
            #line 16 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
	if (!(string.IsNullOrEmpty(ArgBufferInitCode))) {	
            
            #line default
            #line hidden
            this.Write("\r\n\t//各バッファの初期化\r\n");
            
            #line 19 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ArgBufferInit()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
	}	
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
