// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTemplate.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubBufferInitTemplate : StubCodeTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n//バッファの初期化関数\r\n");
            
            #line 9 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubInitializeEntryPoint()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t//呼び出し回数の初期化\r\n\t");
            
            #line 12 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncCalledCountInit()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n\t//戻り値の初期化\r\n\t");
            
            #line 15 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FuncReturnValueInit()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//引数バッファの初期化\r\n\t");
            
            #line 18 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ArgBufferInit()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t//ポインタ引数の戻り値\r\n\t");
            
            #line 21 "E:\development\CStubMk\dev\dev\CodeTemplate\Template\StubBufferInitTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PointerArgBufferInit()));
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
