name: CI test

on: [push, workflow_dispatch]

jobs:
  build:
    name: Run test and build
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build unit test solutions
      run: |
        msbuild /restore ./dev/test/utest/Reader_utest/Reader_utest.sln
        msbuild /m ./dev/test/utest/Reader_utest/Reader_utest.sln /p:Configuration=debug /p:platform="Any CPU"
      
